### ISSUE TITLE
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.

### ISSUE THREAD

**Issue by GIS90** [GIS90/open2lisapi#2]
Sqlalchemy报错信息如下：

[INFO] 127.0.0.1 - - [27/Aug/2022 08:39:48] "POST /dashboard/pan HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gaomingliang/gitee/open2lisapi/deploy/utils/watcher.py", line 83, in _wrapper
    __add_request(request=watcher_args, cost=cost)  # API request to write database table [request]
  File "/Users/gaomingliang/gitee/open2lisapi/deploy/utils/watcher.py", line 70, in __add_request
    request_service.add_request(request=request, cost=cost, rtx=rtx_id)
  File "/Users/gaomingliang/gitee/open2lisapi/deploy/services/request.py", line 172, in add_request
    self.request_bo.add_model(new_model)
  File "/Users/gaomingliang/gitee/open2lisapi/deploy/bo/bo_base.py", line 52, in add_model
    with self.session.begin(subtransactions=True):
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 953, in begin
    self.transaction = self.transaction._begin(nested=nested)
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 317, in _begin
    self._assert_active()
  File "/Users/gaomingliang/gitee/open2lisapi/.venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 283, in _assert_active
    "This session is in 'prepared' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.

**Comment by GIS90** [comment]
原因分析：对于API添加了watcher打点计时器功能，pan【Dashboard面板】、pan_chart【Dashboard面板动态chart】、index【Dashboard实时指标】接口进行查询的时候，在同一db session connection中进行query、insert操作，导致sqlalchemy.exc.InvalidRequestError

**Comment by GIS90** [comment]
目前，解决方案：把pan【Dashboard面板】、pan_chart【Dashboard面板动态chart】、index【Dashboard实时指标】接口注释watcher打点
后续，看看怎么优化

**Comment by GIS90** [comment]
如果是又问题API，使用新RequestService对象
    if hasattr(request, 'endpoint') and getattr(request, 'endpoint') in GLOBAL_NEW_ENDPOINR:
        RequestService().add_request(request=request, cost=cost, rtx=rtx_id)
    else:
        request_service.add_request(request=request, cost=cost, rtx=rtx_id)

**Comment by GIS90** [comment]
解决了
